name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: before install
      run: ./build/tools/before_install.sh
    - name: build
      run: bash build/tools/travis-ci.sh
